name: Build documentation for offline usage
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        branch:
          - 4.x
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
          submodules: true

      - name: ls dependencies
        run: |
          ls -AR

      - name: Install dependencies
        working-directory: /docs
        run: |
          ls -AR
          sudo pip3 install -r requirements.txt
          sudo pip3 install codespell
          sudo apt update
          sudo apt install parallel libwebp7
          sed -i 's/"READTHEDOCS_LANGUAGE", "en"/"READTHEDOCS_LANGUAGE", "zh_CN"/' conf.py
 
      - name: Sphinx - Build HTML
        working-directory: /docs
        run: make SPHINXOPTS='--color' html

      - uses: actions/upload-artifact@v4
        with:
          name: godot-docs-html-${{ matrix.branch }}
          path: /docs/_build/html
          # Keep the current build and the previous build (in case a scheduled build failed).
          # This makes it more likely to have at least one successful build available at all times.
          retention-days: 15

      - name: Sphinx - Build ePub
        working-directory: /docs
        run: |
          # Convert WebP images to PNG and replace references, so that ePub readers can display those images.
          # The ePub 3.0 specification has WebP support, but it's not widely supported by apps and e-readers yet.
          shopt -s globstar nullglob
          parallel --will-cite convert {} {.}.png ::: {about,community,contributing,getting_started,img,tutorials}/**/*.webp
          parallel --will-cite sed -i "s/\\.webp$/\\.png/g" ::: {about,community,contributing,getting_started,tutorials}/**/*.rst

          # Remove banners at the top of each page when building `latest`.
          sed -i 's/"godot_is_latest": True/"godot_is_latest": False/' conf.py
          sed -i 's/"godot_show_article_status": True/"godot_show_article_status": False/' conf.py

          make SPHINXOPTS='--color' epub

      - uses: actions/upload-artifact@v4
        with:
          name: godot-docs-epub-${{ matrix.branch }}
          path: /docs/_build/epub/GodotEngine.epub
          # Keep the current build and the previous build (in case a scheduled build failed).
          # This makes it more likely to have at least one successful build available at all times.
          retention-days: 15

      - name: Update submodules
        run: |
          git submodule update --remote
          git commit -am "Update submodules"
          git push
          
