name: Update submodules
on:
  push:
    branches:
      - 4.x
      
jobs:
  update-submodules:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: ls dependencies
        run: |
          ls -AR


      - name: Update submodules
        run: |
          git submodule update --remote
          git commit -am "Update submodules"
          git push
          


